keys:
  - &admin_uisl 4790A5119BC18FD4
  - &framework age1cvadnquxad325g07fja8k8wkjrlce5wjgwdtu37srl7tf40enaqs8amw4d

creation_rules:
  - path_regex: wifi-secrets.yaml
    key_groups:
      - pgp: [ *admin_uisl ]
        age: [ *framework ]

  - path_regex: hosts/uisl/secrets.yaml
    key_groups:
      - pgp: [ *admin_uisl ]
        age: [ *framework ]
